### ISSUE TITLE
Field definitions coming back empty

### ISSUE THREAD

**Issue by jtalis** [haripriyamurthy/CustomMetadataLoader#1]
Any fields besides standard fields are being rejected in  `CustomMetadataUploadController.cls#isHeaderValid`. This seems to be due to a salesforce bug in Winter '16 - https://success.salesforce.com/issues_view?id=a1p30000000eNxN

**Comment by haripriyamurthy** [comment]
Yes. I noticed this and pushed a new version last week. The app now uses describe instead of querying FieldDefinition. If you get the latest version of the app, you shouldn't see the issue.

**Comment by haripriyamurthy** [comment]
@jtalis Can you please check with the latest version of the app and let me know if it still fails.

**Comment by jtalis** [comment]
That seems to have fixed it.
