### ISSUE TITLE
Namespace Error: Only components in the same namespace as the organization can be created through the API

### ISSUE THREAD

**Issue by mubeen-qawi** [haripriyamurthy/CustomMetadataLoader#10]
Cannot create a new component with the namespace: hortonworks. Only components in the same namespace as the organization can be created through the API

Do you know what is the problem here. I think it should be a straight forward fix

**Comment by mikeconroy** [comment]
This is a duplicate of [this issue](https://github.com/haripriyamurthy/CustomMetadataLoader/issues/4).
It was solved by manually creating the remote site settings in the setup.

**Comment by sjurgis** [comment]
Note this error happens when you have two consequent underscores - hence API interprets this as Namespace rather than record name.
