### ISSUE TITLE
Trying to upload a CSV with fields that contain commas.

### ISSUE THREAD

**Issue by mikeconroy** [haripriyamurthy/CustomMetadataLoader#11]
Some of the field values have commas in them which is causing issues when uploading. I have tried surrounding that field in double quotes and it accepts the field but won't match it to the correct value as it  doesn't remove the double quotes.
Any suggestions?

**Comment by haripriyamurthy** [comment]
Can you please post on https://github.com/forcedotcom/CustomMetadataLoader? Thanks
