### ISSUE TITLE
Error mssg: System.NullPointerException: Attempt to de-reference a null object

### ISSUE THREAD

**Issue by disasterlooms** [haripriyamurthy/CustomMetadataLoader#13]
Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1
Class.CustomMetadataUploadControllerTest.testCreateCustomMetadata: line 44, column 1

I get these errors when running test class in sandbox

**Comment by haripriyamurthy** [comment]
Can you please try the version here - https://github.com/forcedotcom/CustomMetadataLoader
