### ISSUE TITLE
"Attempt to de-reference a null object" - Error Upon Insert of New Custom Metadata

### ISSUE THREAD

**Issue by pmoeller16** [haripriyamurthy/CustomMetadataLoader#14]
Trying to insert a single row into my custom metadata type and received the following error.  Unclear how to resolve at this time.

Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

**Comment by vinita1bisht** [comment]
Hi,

I am getting the same error while using Custom Metadata Loader in sandbox.
Please provide some insights.
Thanks!

**Comment by haripriyamurthy** [comment]
Please issue this version - https://github.com/forcedotcom/CustomMetadataLoader

**Comment by pmoeller16** [comment]
Hi haripriyamurthy,

I clicked the link you provided, downloaded, and deployed the Custom Metadata Loader to my Salesforce sandbox instance a second time.  Please note the sandbox uses the mydomain feature in salesforce.
I tried following the instructions again from the implementation guide, but still receive the following error.

Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

An unexpected error has occurred. Your development organization has been notified.

Please advise

**Comment by mohitrajsfdc** [comment]
@pmoeller16 : Did you find any resolution or any other tool,  as I am also facing the same issue. Any help will be really appreciated!

**Comment by haripriyamurthy** [comment]
@mohitrajsfdc please use this version - https://github.com/forcedotcom/CustomMetadataLoader

**Comment by pankaj90** [comment]
@haripriyamurthy I tried using v2.0 but still I am receiving below error message:

System.NullPointerException: Attempt to de-reference a null object
Error is in expression '{!upsertCustomMetadata}' in component <apex:commandButton> in page custommetadatarecorduploader: Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

Class.MetadataUtil.transformToCustomMetadataAndCreateUpdate: line 114, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateUpdateCmdRecords: line 144, column 1
Class.CustomMetadataUploadController.upsertCustomMetadata: line 52, column 1

**Comment by haripriyamurthy** [comment]
@pankaj90 can you please post the issue on the forcedotcom GitHub.
