### ISSUE TITLE
Wrokbench deployment failed

### ISSUE THREAD

**Issue by rafiepstein** [haripriyamurthy/CustomMetadataLoader#2]
I tried to deploy with Workbench (V34.0) and it failed with the following error:
(I used a test org and I am th eonly user logged in)
Error Status Code   ALREADY_IN_PROCESS

Error Message
null: The changes you requested require salesforce.com to temporarily lock your organization's administration setup. However, the administration setup has already been locked by another change. Please wait for the previous action to finish, then try again later.

Any suggestions?

**Comment by haripriyamurthy** [comment]
From the error message, looks like your org is locked due to another deploy or package install? You can try after that completes.

**Comment by sivainkec** [comment]
Hi,

I am getting below error message.
Errors

Unable to connect to the Salesforce Metadata API.
A Remote Site Setting must be created in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.

**Comment by nevoha** [comment]
me to.

**Comment by haripriyamurthy** [comment]
This is not a bug. A remote site setting is required for the app to make metadata api callouts. You will have to create one. Clicking on the button on that page will create one for you.
