### ISSUE TITLE
Must specify the name in the CustomMetadataType.CustomMetadata format Error

### ISSUE THREAD

**Issue by AlexIsMaking** [haripriyamurthy/CustomMetadataLoader#3]
This issue a is copy of [this](http://salesforce.stackexchange.com/q/114006/10720) question which I've posted on Salesforce Stack Exchange. I've also posted the question in the Custom Metadata Types Sucess Group [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000001t77&fId=0D53000002bkidW). I'll update this issue if someone posts a solution on either site.

I've just deployed the Custom Metadata Loader app to my sandbox and am trying to load my first batch of records for my Custom Metadata Type Interchange_Table__mdt.

When I select the CSV containing my records, the Metadata Type from the type picklist and click Create custom metadata, I get the following error

> Web service callout failed: WebService returned a SOAP Fault: Must specify the name in the CustomMetadataType.CustomMetadata format, Name:Interchange_Table., Delimiter:. faultcode=soapenv:Client faultactor= Error is in expression '{!createCustomMetadata}' in component in page custommetadatarecorduploader: 
> Class.MetadataService.MetadataPort.createMetadata: line 9254, column 1 Class.MetadataUtil.createMetadataAndValidate: line 116, column 1 Class.MetadataUtil.transformToCustomMetadataAndCreate: line 83, column 1 Class.CustomMetadataUploadController.importCSVFileAndCreateCmdRecords: line 120, column 1 Class.CustomMetadataUploadController.createCustomMetadata: line 45, column 1

My spreadsheet looks like this

![metadata spreadsheet example](https://cloud.githubusercontent.com/assets/10284831/13727952/f4b91658-e8fe-11e5-9b95-31f1e232ae95.jpg)

and I can't see any significant difference between this and the sample data which is included in the Github repository which looks like this so I can't work out what's causing the error?

![sample spreadsheet example](https://cloud.githubusercontent.com/assets/10284831/13727953/0be8eb1e-e8ff-11e5-9209-d30f86dfd28b.jpg)

**Comment by haripriyamurthy** [comment]
The label in your sample has a lot of dots and since the app tries to default that to the dev name, it fails. You can add a name column to your csv and it should work.
