### ISSUE TITLE
Error importing custom metadata: Regex too complicated

### ISSUE THREAD

**Issue by mrjcrm** [haripriyamurthy/CustomMetadataLoader#5]
To @haripriyamurthy: Error importing custom metadata: Regex too complicated.
Error is in expression '{!createCustomMetadata}' in component apex:commandButton in page custommetadatarecorduploader: Class.CSVFileUtil.parseCSV: line 17, column 1
Class.CustomMetadataUploadController.importCSVFileAndCreateCmdRecords: line 85, column 1
Class.CustomMetadataUploadController.createCustomMetadata: line 45, column 1

**Comment by haripriyamurthy** [comment]
@sricharananand

**Comment by sricharananand** [comment]
@50471736  Can you please try reducing the size of your csv file, and then doing the import?
