### ISSUE TITLE
SOLVED Error importing custom metadata: Maximum view state size limit (135KB) exceeded.

### ISSUE THREAD

**Issue by mrjcrm** [haripriyamurthy/CustomMetadataLoader#6]
To @haripriyamurthy: "Maximum view state size limit (135KB) exceeded. Actual view state size for this page was 166.469KB"

**Comment by sricharananand** [comment]
Can you please provide more details on how you got this error?

**Comment by mrjcrm** [comment]
To @sricharananand: Here's how I got the error:
- Log into sandbox org using Firefox v47.0 browser
- Click tab 'Custom Metadata Loader'
- Select file '1 (view state size limit exceeded).csv' (see attachment)
- Select mdt type 'SICx_mdt'
- Click button 'Create custom metadata'

[1 (view state size limit exceeded).txt](https://github.com/haripriyamurthy/CustomMetadataLoader/files/369561/1.view.state.size.limit.exceeded.txt)

**Comment by mrjcrm** [comment]
To @sricharananand: If you'd like to see the definition of SICx_mdt, see attachment.

![sicx mdt definition](https://cloud.githubusercontent.com/assets/16543260/16922910/aaff04a0-4ce5-11e6-91e2-b4c2aa03eeb1.png)

**Comment by sricharananand** [comment]
Thanks - How many rows of records are you loading?

**Comment by mrjcrm** [comment]
To @sricharananand: I am trying to load one row.  FYI, orgs are limited to 10 MB of custom metadata.  I don't know if there is a limit to the number of rows.

**Comment by sricharananand** [comment]
i tried with the csv you sent me - i can't seem to repro the issue in my org. The view state error is specific to VF pages, so it has nothing to do with the custom metadata org limit. Also, there is no limit on the number of rows.

**Comment by 50471736** [comment]
This problem can be fixed by modifying VF page 'CustomMetadataRecordUploader' as follows.
Change this line:
<apex:pageBlock rendered="{!showRecordsTable}">
To:
<apex:pageBlock rendered="false">

Cc: @sricharananand, @haripriyamurthy

**Comment by 50471736** [comment]
apex:pageBlock rendered="{!showRecordsTable}"

**Comment by mrjcrm** [comment]
This problem can be fixed by modifying VF page 'CustomMetadataRecordUploader' as follows.

Change this line:
apex:pageBlock rendered="{!showRecordsTable}"

To:
apex:pageBlock rendered="false"

Cc: @sricharananand, @haripriyamurthy
