### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bglasco** [haripriyamurthy/CustomMetadataLoader#7]
he total size of apex code in this application after removing comments exceeds the

**Comment by dp3000** [comment]
When trying to deploy the custom metadata loader, i get the following errors on many of the components:

The total size of apex code in this application after removing comments exceeds the maxiumum character size of 3000000.

What can be done to deploy this application?

**Comment by dp3000** [comment]
@haripriyamurthy

**Comment by haripriyamurthy** [comment]
@sricharananand

**Comment by sricharananand** [comment]
@drewcp87 You are hitting the Apex character size limit for your Salesforce org - please file a Salesforce support ticket asking for increase of the limit. There are other workarounds you can try like the one mentioned in the post below:
https://developer.salesforce.com/forums/?id=906F00000008w0XIAQ
