### ISSUE TITLE
No package.xml found

### ISSUE THREAD

**Issue by isidle** [haripriyamurthy/CustomMetadataLoader#8]
I have tried to deploy the folder "custom_md_loader" but I recieved a "No package.xml found" error for each containing folder.

**Comment by haripriyamurthy** [comment]
@isidle Is this resolved? How did you zip the files? Is package.xml at the top level of the zip file?

**Comment by saulbrodsky** [comment]
I also had this issue. Yes, I zipped the files as you said to and it was unable to find package.xml

**Comment by haripriyamurthy** [comment]
Sorry for the delayed response. Is this resolved?

**Comment by Venkata-Kolla** [comment]
I too got the same issue "No package.xml found", along with some other issues "duplicate value found: <unknown> duplicates value on record with id: <unknown>"

**Comment by haripriyamurthy** [comment]
Can you please post here - https://github.com/forcedotcom/CustomMetadataLoader
